bezkoder:
  app:
    jwtExpirationMs: 86400000
    jwtSecret: bezKoderSecretKey
logging:
  level:
    org:
      hibernate: ERROR
spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost:3306/bookstore
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
